name: Clone Android Kernel 6.12

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git Identity
        run: |
          git config --global user.name "Arkael-Dev"
          git config --global user.email "kingfinix98@gmail.com"

      - name: Clone Android Common Kernel
        run: |
          cd ~
          # TAMBAHKAN --depth=1 agar hanya mengambil commit terakhir (shallow clone)
          git clone --branch android16-6.12 --depth=1 https://android.googlesource.com/kernel/common

      - name: Push to GitHub
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd ~/common

          git remote remove origin || true

          git remote add origin https://x-access-token:${TOKEN}@github.com/Arkael-Dev/android-kernel-common16.6.12.git

          git push -u origin android16-6.12 --force
